### ISSUE TITLE
support sentry-cocoa v8.8.0

### ISSUE THREAD

**Issue by jycmashiro** [getsentry/sentry-kotlin-multiplatform#119]
### Problem Statement

can't work with RNSentry v5.7.1

**Comment by romtsn** [comment]
hi @jycmashiro we'd need more details here - what exactly doesn't work? Are you using sentry-react-native or sentry-kotlin-multiplatform? Please provide as much details as possible, otherwise we won't be able to help you.

**Comment by buenaflor** [comment]
It's definitely possible but the downside I see is that all current users would need to manually update their cocoa deps to 8.8.0 as well. Not sure if there is a smooth way to transfer that information other than through the SDK changelog and docs? What do you think @romtsn

**Comment by buenaflor** [comment]
We will bump the versions occasionally but cannot guarantee that the versions will work with your usage. Currently we do not support the usage of multiple hybrid SDKs. However in the future we might plan to sync the bumping of the Cocoa SDK with our React Native SDKs so that we minimize these issues to a certain extent.
