### ISSUE TITLE
Update Sentry SDK version

### ISSUE THREAD

**Issue by Legion2** [getsentry/sentry-kotlin-multiplatform#46]
On sentry.io we get a notification to update the sentry SDK, but there is no newer version of this library with the latest SDK version. Can you please update the sentry SDK version.

**Comment by romtsn** [comment]
Which version does it tell you to update to?

**Comment by Legion2** [comment]
> We recommend you [update your SDK from sentry.java.android@v6.9.1 to sentry.java.android@v6.14.0](https://docs.sentry.io/platforms/android?_ga=2.173632163.1467163140.1676899227-1907607188.1675679404) (All sentry packages should be updated and their versions should match)

**Comment by romtsn** [comment]
Alright, this is unrelated to this SDK, because it tells you to update the Android SDK. Once we officially publish the KMP SDK to our package registry, it will correctly identify which SDK you're using and won't show the warning anymore.

This is a flaw of the SDK being experimental, so I'm gonna close this for now.
